### ISSUE TITLE
about:addons-memory no longer a "valid" address?

### ISSUE THREAD

**Issue by Trilkhai** [intika/about-addons-memory-pm#1]
I've used your extension for a long time, but after not accessing it for a few months, I clicked on my usual bookmark (to about:addons-memory) tonight and was surprised to get a standard Problem Loading Page:

> **The address isn't valid**
> The URL is not valid and cannot be loaded.
>     Web addresses are usually written like http://www.example.com/
>     Make sure that you’re using forward slashes (i.e. /)..

I double-checked to make sure that the latest version of your extension (12.8) is installed & active.  Then, just in case my old bookmark might be wrong, I installed the button extension that was mentioned in this extension's thread on the Pale Moon forum, but choosing "Addons Memory Usage Page" from its drop-down menu points to the same "invalid" location.

All other "about:" addresses, including about:memory, do work.

Browser info:
Name: 	Pale Moon
Version: 	28.1.0 (64-bit)
Build ID: 	20180918173640
Update Channel:	release
User Agent: 	Mozilla/5.0 (X11; Linux x86_64; rv:52.9) Gecko/20100101 Goanna/4.1 Firefox/52.9 PaleMoon/28.1.0
OS: 	Linux 4.4.4-pclos1

Is there anything I can try to get it working, or other info you would find useful?

**Comment by intika** [comment]
my version does not work any more... i am planning to work on my PM extensions but it's not for soon. 

Awaiting a new version here is a a version that work with v28xx 

https://github.com/intika/about-addons-memory-pm/blob/master/about-addons-memory%40tn123.org.xpi

It does not have all the features but it works... 

Related :
about:addons-memory
about:performance
about:memory

**Comment by intika** [comment]
some users have reported that v12.9 is working... have a look at it in https://github.com/intika/about-addons-memory-pm/releases

https://forum.palemoon.org/viewtopic.php?f=44&t=20050
